name: Demo – configurable instance for debugging
on:
  workflow_dispatch:
  workflow_call:   # Tested by `demos.yml`
permissions:
  id-token: write  # Required for AWS OIDC authentication
  contents: read   # Required for actions/checkout
jobs:
  ec2:
    # To use from another repo: Open-Athena/ec2-gha/.github/workflows/runner.yml
    uses: ./.github/workflows/runner.yml
    secrets: inherit
  gpu-test:
    needs: ec2
    runs-on: ${{ needs.ec2.outputs.id }}
    steps:
    - run: nvidia-smi  # Verify GPU is available
