name: Demo – multiple jobs on one EC2 instance, in sequence
on:
  workflow_dispatch:
jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Placeholder workflow – being developed in \#2 / rw/hooks branch"
