name: Run All Demos
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  demo-gpu-minimal:
    uses: ./.github/workflows/demo-gpu-minimal.yml
    secrets: inherit
  demo-gpu-job-seq:
    uses: ./.github/workflows/demo-gpu-job-seq.yml
    secrets: inherit
  demo-archs:
    uses: ./.github/workflows/demo-archs.yml
    secrets: inherit
  demo-matrix-wide:
    uses: ./.github/workflows/demo-matrix-wide.yml
    secrets: inherit
  demo-multi-instance:
    uses: ./.github/workflows/demo-multi-instance.yml
    secrets: inherit
  demo-multi-job:
    uses: ./.github/workflows/demo-multi-job.yml
    secrets: inherit
