name: Demo – multiple runners on one instance
on:
  workflow_dispatch:
jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Placeholder workflow – being developed in #2 / rw/hooks branch"
