name: Demo – minimal EC2 GPU runner
on:
  workflow_dispatch:
jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Placeholder workflow – being developed in \#2 / rw/hooks branch"
