name: Demo – OS/Architecture sweep (CPU nodes)
on:
  workflow_dispatch:
    inputs:
      sleep:
        description: "Sleep duration in seconds for workload simulation"
        required: false
        type: string
        default: "10"
  workflow_call:   # Can be called from other workflows
    inputs:
      sleep:
        required: false
        type: string
        default: "10"
permissions:
  id-token: write  # Required for AWS OIDC authentication
  contents: read   # Required for actions/checkout
jobs:
  os-arch-matrix:
    name: ${{ matrix.os }} ${{ matrix.version }} ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { "os": Ubuntu, "version": "22.04", "arch": x86_64, "ami": ami-021589336d307b577, "instance_type":  t3.medium }
          - { "os": Ubuntu, "version": "22.04", "arch":  arm64, "ami": ami-06daf9c2d2cf1cb37, "instance_type": t4g.medium }
          - { "os": Ubuntu, "version": "24.04", "arch": x86_64, "ami": ami-0ca5a2f40c2601df6, "instance_type":  t3.medium }
          - { "os": Ubuntu, "version": "24.04", "arch":  arm64, "ami": ami-0aa307ed50ca3e58f, "instance_type": t4g.medium }
          - { "os": Debian, "version":    "11", "arch": x86_64, "ami": ami-0e6612f57082e7ea4, "instance_type":   t3.large }
          - { "os": Debian, "version":    "11", "arch":  arm64, "ami": ami-0c3f5b0b87f042da8, "instance_type":  t4g.large }
          - { "os": Debian, "version":    "12", "arch": x86_64, "ami": ami-05b50089e01b13194, "instance_type":   t3.large }
          - { "os": Debian, "version":    "12", "arch":  arm64, "ami": ami-0505441d7e1514742, "instance_type":  t4g.large }
          - { "os":    AL2, "version":     "2", "arch": x86_64, "ami": ami-0e2c86481225d3c51, "instance_type":   t3.small }
          - { "os":    AL2, "version":     "2", "arch":  arm64, "ami": ami-08333c9352b93f31e, "instance_type":  t4g.small }
          - { "os": AL2023, "version":  "2023", "arch": x86_64, "ami": ami-00ca32bbc84273381, "instance_type":   t3.small }
          - { "os": AL2023, "version":  "2023", "arch":  arm64, "ami": ami-0aa7db6294d00216f, "instance_type":  t4g.small }
    uses: ./.github/workflows/demo-dbg-minimal.yml
    with:
      type: ${{ matrix.instance_type }}
      ami: ${{ matrix.ami }}
      sleep: ${{ inputs.sleep }}
    secrets: inherit
